language: node_js
node_js: '7'
script: yarn build
before_deploy:
- rm -rf .git
- rm .babelrc
- rm .eslintrc
- rm .gitignore
- rm .travis.yml
- rm build.js
- rm LICENSE.md
- rm README.md
- rm webpack.config.js
- rm yarn.lock
- git init
- git config user.name "travis"
- git config user.email "vojtechstepancik@outlook.com"
- echo node_modules > .gitignore
- git add .
- git commit -m "$TRAVIS_COMMIT"
deploy:
  skip-cleanup: true
  provider: azure_web_apps
  on: express
  site: uncannylobsters
  slot: wip
