language: node_js
node_js: '7'
script: yarn build
before_deploy:
- rm -rf node_modules
- rm .babelrc
- rm .eslintrc
- rm .gitignore
- rm .travis.yml
- rm build.js
- rm LICENSE.md
- rm README.md
- rm webpack.config.js
- rm yarn.lock
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  on: express
  site: uncannylobsters
  slot: uncannylobsters-wip
  verbose: true
  username:
    secure: Hf+ZUdwKRtLWg36VHju4gnfLaq2c/7xDtX6ekSwd9mbI7TviilBmjoM3k6NNVUl9Ykh2CT8HOaBUUvyep1mxa6lpvFETZCf/DGJdWfHzwCUspITYxv1y+LX3xHbuPqhTEN9zEx1YZ10koNBtQnzcTjGB6I8gmw40ltRoaPMRNmno/2TuldTMf6JLvZcPGiNlnp9IsLazl+45x41548v43ji8dPW3+Yz8CnwT/Z3LPNv+aSGzDJz7eO2daLMrdD0mYcazZxEzMxZWCXgzWa7PJYQLxo7jtDNQKl3mMYp5HejS9D0hLB96xjSi+jhVIKs8LrPR015HxFFP75XCI83Kg2yjo4h8ArsdI3QbM8rAR7gzA9Lxx2K93hUOs1VcO4vZ3iv7pc1JNqQYC1yU7lxXR410dMV2Pxq5lNbeCNu5FM+coBq6oAchzcLanGcJy4HLSE7YR206uooHulvuU31f4T5MgDOmf1VfG3J2VUnFtr0rKM6zx28yZZtGkjMBxwJLE52R1fVwbsnuIEzjobYa7oRAU+bIsVsYKzRRN3gOJgNPGuUp1S/xcA7EzjXHOv9mVrFZXT1QicJVfTbkPEoZetZiaJZMp9nHjGvYgHN/i2reE7xhqcA83clkzm7DcezJU/UsKaGObY53wgvuNphcLrKrgk4GYWAhw/oIrZwg0ek=
  password:
    secure: GcvbxNW4FujyH7aaiHXBHGfq/keOaEOfvY+9ivIeJwSn+SuqZbcpPpqKesW86K2/eJuUq2S/nybCdlDO/sVuBBjgZKhIWj1+KBlaCr4FZl5/o1NW2X9fnRd3K0q5hIFMXnmDmYxozuLnKHsPVjSGcbrompyJzbPG4h4R8fA1zYnGxus7LVuuagOlEJhg3omSx3bD1IuolR/6DM1lA8PezLN5OS3A6uR/zp1hsiKx1WXjmwzQIvAKK+BzlKmr08pxrtcF2z+7McRcWSl2N007GnKt4neodjQZzRTTzEezPXOF7+wSD/+ym5AH16xxnlG1NE4jNorjD39YzjtWC80rpFefxX0uC4lr+Z5dbVijW/mo7p67wi42Z7OKIjO/vbWASXIphj7XTOf0IWyP2tS2Gala0H+bRkW7b6eiU9uEyr8kIBsrIbbhXjCoX4Eq8rnrIWACUoAxsRMfBCaC7kmrw1tS+mC80JgUGex5mRaZXxYmmPdU+c5raet7EYH/8Egjrx8TVrXx9tOvAETX8AsR9z+yV35hv6B9Yu/mOFD4qXQkDO5xgUnmGTZDaqodmX+LZ+GHiEzCFDU5daD9RIsrZMENRnuuGPJnXZdhQCzIrPYmWgpMAJGvrRYxCtCBIG4MxfBTbwOuNgLOYKABUExF9cMzD1pHOz2sXPZ89J/Dc1Q=
