language: node_js
node_js: '7'
script: yarn build
before_deploy:
- rm -rf node_modules
- rm -rf .git
- rm .eslintrc
- rm .gitignore
- rm .travis.yml
- rm build.js
- rm LICENSE.md
- rm README.md
- rm webpack.config.js
- rm yarn.lock
- git init
- git config user.name "travis"
- git config user.email "vojtechstepancik@outlook.com"
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  site: uncannylobsters
  slot: uncannylobsters
